#!/usr/bin/env bash
# 把 tgoskits 子模块当前分支相对 PIN_COMMIT 的所有 commit
# 提取成 patch 文件，写入 patches/<task-id>/。
#
# 用法：
#   scripts/extract-patches.sh T1-execve-mt        # 提取到 patches/T1-execve-mt/
#   scripts/extract-patches.sh T1-execve-mt --dry  # 只打印不写
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

TASK="${1:-}"
[[ -n "$TASK" ]] || die "usage: extract-patches.sh <task-id> [--dry]"
DRY=0
[[ "${2:-}" == "--dry" ]] && DRY=1

OUT="$PATCHES/$TASK"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

cd "$TGOSKITS"

NCOMMITS=$(git rev-list --count "$PIN_COMMIT..HEAD" 2>/dev/null || echo 0)
[[ "$NCOMMITS" -gt 0 ]] || die "no commits between $PIN_COMMIT..HEAD; nothing to extract"

log "extracting $NCOMMITS commits to $OUT"
git format-patch --output-directory "$TMP" --no-signature --no-stat \
    --zero-commit --no-numbered \
    "$PIN_COMMIT..HEAD" >/dev/null

# 按生成顺序重新编号成 0001/0002/...
i=1
mkdir -p "$OUT"
if (( ! DRY )); then
    rm -f "$OUT"/*.patch 2>/dev/null || true
fi
for p in "$TMP"/*.patch; do
    base="$(basename "$p")"
    # 去掉 git 自动加的 0001- 等前缀
    clean="${base#[0-9][0-9][0-9][0-9]-}"
    target="$(printf '%s/%04d-%s' "$OUT" "$i" "$clean")"
    if (( DRY )); then
        echo "would write: $target"
    else
        cp "$p" "$target"
        echo "wrote: $target"
    fi
    ((i++))
done

# 写 metadata
if (( ! DRY )); then
    {
        echo "# generated by scripts/extract-patches.sh"
        echo "task = \"$TASK\""
        echo "base_commit = \"$PIN_COMMIT\""
        echo "extracted_at = \"$(date -Iseconds)\""
        echo "n_commits = $NCOMMITS"
    } > "$OUT/META.toml"
fi
log "done: $OUT"
